version: "3.9"
services:
  backend:
    build: ./backend
    container_name: cloud-backend
    env_file:
      - ./backend/.env.example
    environment:
      - STORAGE_DIR=/data/blobs
      - DATABASE_URL=sqlite:///data/app.db
      - ALLOW_ORIGINS=*
    volumes:
      - ./backend/data:/data
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: cloud-frontend
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
