apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-backend
  namespace: cloud-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-backend
  template:
    metadata:
      labels:
        app: cloud-backend
    spec:
      containers:
        - name: backend
          image: yourrepo/cloud-backend:latest
          env:
            - name: STORAGE_DIR
              value: /data/blobs
            - name: DATABASE_URL
              value: sqlite:////data/app.db
            - name: ALLOW_ORIGINS
              value: "*"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cloud-storage-pvc
